### ISSUE TITLE
Support fungible-token transfer

### ISSUE THREAD

**Issue by Trave11ingPoet** [bianjieai/tibc#14]
Hi, Bianjieai team. I know you from [cosmos blog](https://blog.cosmos.network/interchain-grantee-spotlight-how-bianjie-is-helping-to-grow-the-cosmos-ecosystem-44a5a75eb63b) and respect your great work. But I found that TIBC only supports cross-chain NFT transfer. I want to add the support for cross-chain fungible-token transfer. Can i take it? @haifengxi @zhangyelong

**Comment by haifengxi** [comment]
Please join our Discord at https://discord.gg/bmhu9F9xbX and find us there:
Harvey | IRISnet#4037, Mitch | IRISnet#2643

**Comment by Trave11ingPoet** [comment]
> Please join our Discord at https://discord.gg/bmhu9F9xbX and find us there:
> Harvey | IRISnet#4037, Mitch | IRISnet#2643

Thank you for your reply, got it.
